# Generated by Django 4.0.6 on 2022-07-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_tag_project_vote_ratio_project_vote_total_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('UP', 'UP VOTE'), ('dOWN', 'DOWN VOTE')], max_length=200),
        ),
    ]
